### ISSUE TITLE
JWT::DecodeError (Nil JSON web token)

### ISSUE THREAD

**Issue by paladiy** [XeroAPI/xero-oauth2-omniauth-strategy#1]
We are building application that will use xero oauth2 to work with it's api, but we've faced an issue while integrating your gem. 

On the success callback it raises error: `JWT::DecodeError (Nil JSON web token)` 

The issue happens in the following code: 

```
def raw_info
  decoded_info ||= JWT.decode access_token['id_token'], nil, false
  @raw_info ||= decoded_info[0]
end

```

but AccessToken object does not have `id_token` attribute. 

See full trace below: 

```Started GET "/auth/xero/callback?code=a3dcb1bbe770fbf8f4fd20d1e5fbdf636cc831cdb5a9729729fad04c165407d2&scope=accounting.transactions.read%20accounting.reports.read%20accounting.journals.read%20accounting.settings.read%20accounting.contacts.read%20accounting.attachments.read&state=29a0f57e024f6de5924975cc1d8617b8c104308df6580d96" for ::1 at 2019-10-12 12:26:38 +0200
(xero) Callback phase initiated.

JWT::DecodeError (Nil JSON web token):

jwt (2.1.0) lib/jwt.rb:26:in `decode'
omniauth-xero-oauth2 (0.9.0) lib/omniauth/strategies/xero_oauth2.rb:47:in `raw_info'
omniauth-xero-oauth2 (0.9.0) lib/omniauth/strategies/xero_oauth2.rb:39:in `block in <class:XeroOauth2>'
omniauth (1.9.0) lib/omniauth/strategy.rb:109:in `instance_eval'
omniauth (1.9.0) lib/omniauth/strategy.rb:109:in `block in compile_stack'
omniauth (1.9.0) lib/omniauth/strategy.rb:108:in `each'
omniauth (1.9.0) lib/omniauth/strategy.rb:108:in `inject'
omniauth (1.9.0) lib/omniauth/strategy.rb:108:in `compile_stack'
omniauth (1.9.0) lib/omniauth/strategy.rb:102:in `uid_stack'
omniauth (1.9.0) lib/omniauth/strategy.rb:332:in `uid'
omniauth (1.9.0) lib/omniauth/strategy.rb:348:in `auth_hash'
omniauth (1.9.0) lib/omniauth/strategy.rb:372:in `callback_phase'
omniauth-oauth2 (1.6.0) lib/omniauth/strategies/oauth2.rb:75:in `callback_phase'
omniauth (1.9.0) lib/omniauth/strategy.rb:238:in `callback_call'
omniauth (1.9.0) lib/omniauth/strategy.rb:189:in `call!'
omniauth (1.9.0) lib/omniauth/strategy.rb:169:in `call'
omniauth (1.9.0) lib/omniauth/strategy.rb:192:in `call!'
omniauth (1.9.0) lib/omniauth/strategy.rb:169:in `call'
omniauth (1.9.0) lib/omniauth/strategy.rb:192:in `call!'
omniauth (1.9.0) lib/omniauth/strategy.rb:169:in `call'
omniauth (1.9.0) lib/omniauth/strategy.rb:192:in `call!'
omniauth (1.9.0) lib/omniauth/strategy.rb:169:in `call'
omniauth (1.9.0) lib/omniauth/strategy.rb:192:in `call!'
omniauth (1.9.0) lib/omniauth/strategy.rb:169:in `call'
omniauth (1.9.0) lib/omniauth/builder.rb:64:in `call'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:57:in `block in call'
activesupport (6.0.0.rc1) lib/active_support/notifications.rb:182:in `instrument'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:56:in `call'
rack (2.0.7) lib/rack/tempfile_reaper.rb:15:in `call'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:57:in `block in call'
activesupport (6.0.0.rc1) lib/active_support/notifications.rb:182:in `instrument'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:56:in `call'
rack (2.0.7) lib/rack/etag.rb:25:in `call'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:57:in `block in call'
activesupport (6.0.0.rc1) lib/active_support/notifications.rb:182:in `instrument'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:56:in `call'
rack (2.0.7) lib/rack/conditional_get.rb:25:in `call'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:57:in `block in call'
activesupport (6.0.0.rc1) lib/active_support/notifications.rb:182:in `instrument'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:56:in `call'
rack (2.0.7) lib/rack/head.rb:12:in `call'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:57:in `block in call'
activesupport (6.0.0.rc1) lib/active_support/notifications.rb:182:in `instrument'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:56:in `call'
actionpack (6.0.0.rc1) lib/action_dispatch/http/content_security_policy.rb:18:in `call'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:57:in `block in call'
activesupport (6.0.0.rc1) lib/active_support/notifications.rb:182:in `instrument'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:56:in `call'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:57:in `block in call'
activesupport (6.0.0.rc1) lib/active_support/notifications.rb:182:in `instrument'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:56:in `call'
rack (2.0.7) lib/rack/session/abstract/id.rb:232:in `context'
rack (2.0.7) lib/rack/session/abstract/id.rb:226:in `call'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:57:in `block in call'
activesupport (6.0.0.rc1) lib/active_support/notifications.rb:182:in `instrument'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:56:in `call'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/cookies.rb:644:in `call'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:57:in `block in call'
activesupport (6.0.0.rc1) lib/active_support/notifications.rb:182:in `instrument'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:56:in `call'
activerecord (6.0.0.rc1) lib/active_record/migration.rb:567:in `call'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:57:in `block in call'
activesupport (6.0.0.rc1) lib/active_support/notifications.rb:182:in `instrument'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:56:in `call'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
activesupport (6.0.0.rc1) lib/active_support/callbacks.rb:101:in `run_callbacks'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:57:in `block in call'
activesupport (6.0.0.rc1) lib/active_support/notifications.rb:182:in `instrument'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:56:in `call'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:57:in `block in call'
activesupport (6.0.0.rc1) lib/active_support/notifications.rb:182:in `instrument'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:56:in `call'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/actionable_exceptions.rb:17:in `call'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:57:in `block in call'
activesupport (6.0.0.rc1) lib/active_support/notifications.rb:182:in `instrument'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:56:in `call'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/debug_exceptions.rb:32:in `call'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:57:in `block in call'
activesupport (6.0.0.rc1) lib/active_support/notifications.rb:182:in `instrument'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:56:in `call'
web-console (4.0.0) lib/web_console/middleware.rb:132:in `call_app'
web-console (4.0.0) lib/web_console/middleware.rb:28:in `block in call'
web-console (4.0.0) lib/web_console/middleware.rb:17:in `catch'
web-console (4.0.0) lib/web_console/middleware.rb:17:in `call'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:57:in `block in call'
activesupport (6.0.0.rc1) lib/active_support/notifications.rb:182:in `instrument'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:56:in `call'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:57:in `block in call'
activesupport (6.0.0.rc1) lib/active_support/notifications.rb:182:in `instrument'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:56:in `call'
railties (6.0.0.rc1) lib/rails/rack/logger.rb:38:in `call_app'
railties (6.0.0.rc1) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.0.0.rc1) lib/active_support/tagged_logging.rb:80:in `block in tagged'
activesupport (6.0.0.rc1) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (6.0.0.rc1) lib/active_support/tagged_logging.rb:80:in `tagged'
railties (6.0.0.rc1) lib/rails/rack/logger.rb:26:in `call'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:57:in `block in call'
activesupport (6.0.0.rc1) lib/active_support/notifications.rb:182:in `instrument'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:56:in `call'
sprockets-rails (3.2.1) lib/sprockets/rails/quiet_assets.rb:13:in `call'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:57:in `block in call'
activesupport (6.0.0.rc1) lib/active_support/notifications.rb:182:in `instrument'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:56:in `call'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:57:in `block in call'
activesupport (6.0.0.rc1) lib/active_support/notifications.rb:182:in `instrument'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:56:in `call'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/request_id.rb:27:in `call'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:57:in `block in call'
activesupport (6.0.0.rc1) lib/active_support/notifications.rb:182:in `instrument'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:56:in `call'
rack (2.0.7) lib/rack/method_override.rb:22:in `call'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:57:in `block in call'
activesupport (6.0.0.rc1) lib/active_support/notifications.rb:182:in `instrument'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:56:in `call'
rack (2.0.7) lib/rack/runtime.rb:22:in `call'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:57:in `block in call'
activesupport (6.0.0.rc1) lib/active_support/notifications.rb:182:in `instrument'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:56:in `call'
activesupport (6.0.0.rc1) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:57:in `block in call'
activesupport (6.0.0.rc1) lib/active_support/notifications.rb:182:in `instrument'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:56:in `call'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:57:in `block in call'
activesupport (6.0.0.rc1) lib/active_support/notifications.rb:182:in `instrument'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:56:in `call'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/static.rb:126:in `call'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:57:in `block in call'
activesupport (6.0.0.rc1) lib/active_support/notifications.rb:182:in `instrument'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:56:in `call'
rack (2.0.7) lib/rack/sendfile.rb:111:in `call'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:57:in `block in call'
activesupport (6.0.0.rc1) lib/active_support/notifications.rb:182:in `instrument'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:56:in `call'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/host_authorization.rb:83:in `call'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:57:in `block in call'
activesupport (6.0.0.rc1) lib/active_support/notifications.rb:182:in `instrument'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:56:in `call'
rack-cors (1.0.3) lib/rack/cors.rb:95:in `call'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:57:in `block in call'
activesupport (6.0.0.rc1) lib/active_support/notifications.rb:182:in `instrument'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:56:in `call'
webpacker (4.0.2) lib/webpacker/dev_server_proxy.rb:29:in `perform_request'
rack-proxy (0.6.5) lib/rack/proxy.rb:57:in `call'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:57:in `block in call'
activesupport (6.0.0.rc1) lib/active_support/notifications.rb:182:in `instrument'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:56:in `call'
railties (6.0.0.rc1) lib/rails/engine.rb:526:in `call'
puma (3.12.1) lib/puma/configuration.rb:227:in `call'
puma (3.12.1) lib/puma/server.rb:660:in `handle_request'
puma (3.12.1) lib/puma/server.rb:474:in `process_client'
puma (3.12.1) lib/puma/server.rb:334:in `block in run'
puma (3.12.1) lib/puma/thread_pool.rb:135:in `block in spawn_thread'
```

**Comment by jenksguo** [comment]
Hi paladiy, 

Thanks for reporting this error. This error occurs probably because I have written the strategy assuming JWT is always returning from Xero auth server, in another word, the app will always pass in openid scope.  

Could you please share the scope you have passed in to confirm?

I will make an improvement to the code so the  decoder only execute when the 0access_token['id_token'] is not nil.

**Comment by paladiy** [comment]
@jenksguo seems like it is a reason. We do not have `openid` scope in the list. Here is our one: 

```
scope: 'accounting.transactions.read ' \
      'accounting.reports.read ' \
      'accounting.journals.read ' \
      'accounting.settings.read ' \
      'accounting.contacts.read ' \
      'accounting.attachments.read ' \
      'offline_access'
```

Thank you for quick response and pointing to the problem

**Comment by jenksguo** [comment]
Hi paladiy, 

I have made the gem work with the scope without openid. 

Please update your gem (via rubygem.org) to: 
v0.9.1 - October 16, 2019 (5 KB)

or use this repo as a local dependency.

**Comment by jenksguo** [comment]
@paladiy , please use the v0.9.2 instead of v0.9.1. v0.9.1 only works with scope without openid, whereas in v0.9.2 will work with any scope.

**Comment by paladiy** [comment]
Thank you for letting us know. we’ll update to most recent version
